######################################################################
##
## Filename: E_TRANSMITT.udo
## Created on: Sun Dec 05 16:45:00 Mitteleuropäische Zeit 2010
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
